import XCTest
@testable import AACCore

final class GameSettingsTests: XCTestCase {
    let header = "-- [SYSTEM CONFIGURATION]\n-- WARNING! THIS FILE IS GENERATED BY THE SYSTEM! EDITING IS NOT RECOMMENDED!\nlocale = en_us\ncl_serveraddr = 1.2.3.4\n"

    func testDefaults() {
        let d = Dictionary(uniqueKeysWithValues: GameSettings.defaults(width: 1512, height: 945).map { ($0.key, $0.value) })
        XCTAssertEqual(d["r_driver"], "\"DX9\"")
        XCTAssertEqual(d["r_fullscreen"], "0")
        XCTAssertEqual(d["r_width"], "1512")
        XCTAssertEqual(d["r_height"], "945")
        XCTAssertEqual(d["option_use_shadow"], "0")
        XCTAssertEqual(d["r_multithreaded"], "1")
        XCTAssertEqual(d["sys_spec_full"], "2")
    }

    func testAddsMissingKeysAndKeepsOthers() {
        let out = GameSettings.merge(header, [("r_driver", "\"DX9\"")], overwrite: false)
        XCTAssertTrue(out.hasPrefix(header))
        XCTAssertEqual(GameSettings.value(of: "r_driver", in: out), "\"DX9\"")
        XCTAssertEqual(GameSettings.value(of: "locale", in: out), "en_us")
    }

    func testKeepsUserValueRegardlessOfCase() {
        let text = header + "r_fullscreen = 1\n"
        let out = GameSettings.merge(text, [("r_Fullscreen", "0")], overwrite: false)
        XCTAssertEqual(GameSettings.value(of: "r_Fullscreen", in: out), "1")
        XCTAssertEqual(out.components(separatedBy: "ullscreen").count - 1, 1, "no duplicate key")
    }

    func testOverwriteReplacesInPlace() {
        let text = header + "r_fullscreen = 1\nr_driver = \"DX10\"\n"
        let out = GameSettings.merge(text, [("r_Fullscreen", "0"), ("r_driver", "\"DX9\"")], overwrite: true)
        XCTAssertEqual(GameSettings.value(of: "r_fullscreen", in: out), "0")
        XCTAssertEqual(GameSettings.value(of: "r_driver", in: out), "\"DX9\"")
        XCTAssertEqual(out.components(separatedBy: "r_driver").count - 1, 1)
    }

    func testEmptyFile() {
        let out = GameSettings.merge("", [("a", "1")], overwrite: false)
        XCTAssertEqual(out, "a = 1\n")
    }

    func testOverwriteReplacesEveryCopyOfAKey() {
        let text = header + "r_fullscreen = 0\nlocale = en_us\nr_Fullscreen = 0\n"
        let out = GameSettings.merge(text, [("r_fullscreen", "1")], overwrite: true)
        XCTAssertEqual(out.lowercased().components(separatedBy: "r_fullscreen").count - 1, 1)
        XCTAssertEqual(GameSettings.value(of: "r_fullscreen", in: out), "1")
        XCTAssertEqual(GameSettings.value(of: "locale", in: out), "en_us")
    }

    func testRemovingDuplicatesKeepsTheGamesOwnFirstLine() {
        let text = header + "r_fullscreen = 1\nr_width = 3024\nr_vsync = 1\nr_Fullscreen = 0\nr_Width = 1512\n"
        let out = GameSettings.removingDuplicates(text)
        XCTAssertEqual(out, header + "r_fullscreen = 1\nr_width = 3024\nr_vsync = 1\n")
    }
}
